# Generated by Django 4.0.6 on 2024-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='home/greystatistic/Ins_Lautaro/static/images/profesores'),
        ),
    ]
