# Generated by Django 4.0.6 on 2024-10-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_alter_profesor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profesores'),
        ),
    ]
