# Generated by Django 4.0.6 on 2024-10-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_alter_profesor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
