# Generated by Django 4.0.6 on 2024-10-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_alter_profesor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='Foto1',
            field=models.ImageField(blank=True, null=True, upload_to='images/actividades/'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='Foto2',
            field=models.ImageField(blank=True, null=True, upload_to='images/actividades/'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='Foto3',
            field=models.ImageField(blank=True, null=True, upload_to='images/actividades/'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/estudiantes/'),
        ),
        migrations.AlterField(
            model_name='atenciones',
            name='Foto1Evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='images/atenciones/'),
        ),
        migrations.AlterField(
            model_name='atenciones',
            name='Foto2Evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='images/atenciones/'),
        ),
        migrations.AlterField(
            model_name='atenciones',
            name='Foto3Evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='images/atenciones/'),
        ),
        migrations.AlterField(
            model_name='consejosprofesores',
            name='Archivo1Consejo',
            field=models.ImageField(blank=True, null=True, upload_to='images/consejos/'),
        ),
        migrations.AlterField(
            model_name='consejosprofesores',
            name='Archivo2Consejo',
            field=models.ImageField(blank=True, null=True, upload_to='images/consejos/'),
        ),
        migrations.AlterField(
            model_name='consejosprofesores',
            name='Archivo3Consejo',
            field=models.ImageField(blank=True, null=True, upload_to='images/consejos/'),
        ),
        migrations.AlterField(
            model_name='impresiones',
            name='Archivo1Impresion',
            field=models.ImageField(blank=True, null=True, upload_to='images/impresiones/'),
        ),
        migrations.AlterField(
            model_name='impresiones',
            name='Archivo2Impresion',
            field=models.ImageField(blank=True, null=True, upload_to='images/impresiones/'),
        ),
        migrations.AlterField(
            model_name='impresiones',
            name='Archivo3Impresion',
            field=models.ImageField(blank=True, null=True, upload_to='images/impresiones/'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='Foto1Insumo',
            field=models.ImageField(blank=True, null=True, upload_to='images/insumos/'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='Foto2Insumo',
            field=models.ImageField(blank=True, null=True, upload_to='images/insumos/'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='Foto3Insumo',
            field=models.ImageField(blank=True, null=True, upload_to='images/insumos/'),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='FotoPrestamo',
            field=models.ImageField(blank=True, null=True, upload_to='images/prestamos/'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/profesores/'),
        ),
    ]
