# Generated by Django 4.0.6 on 2024-10-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_alter_actividades_foto1_alter_actividades_foto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
