# Generated by Django 4.0.6 on 2024-10-07 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('horarios', '0009_alter_profesor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='FechaHoraRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='Observacion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='Profesor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='Administrativo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='FechaHoraRegistroMatriculaEstudiante',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atenciones',
            name='FechaHoraRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atenciones',
            name='Motivo',
            field=models.TextField(choices=[('CITACION', 'CITACION'), ('DESCONPENSACION', 'DESCONPENSACION'), ('URGENCIA', 'URGENCIA'), ('SOLICITUD', 'SOLICITUD'), ('OTRA', 'OTRA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='atenciones',
            name='Profesional',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='Administrativo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='FechaHoraRegistroCertificado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consejosprofesores',
            name='Administrativo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consejosprofesores',
            name='ComentariosConsejo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consejosprofesores',
            name='FechaHoraRegistroConsejo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='impresiones',
            name='FechaHoraRegistroImpresion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='impresiones',
            name='ProfesorImpresion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='DetalleInsumo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='Administrativo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='DetallePrestamo',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='FechaHoraRegistroPrestamo',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
